apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: todo-app-deployment
  name: todo-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todo-app-deployment
    spec:
      containers:
      - image: registry.gitlab.com/myatty1/microservice/todo-app/todo-app:5246a97022cb195823c57cc60003b886e82f52f8
        name: todo-app
        resources: {}
status: {}
