apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: todo-app-deployment
  name: todo-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todo-app-deployment
    spec:
      containers:
        - image: registry.gitlab.com/myatty1/microservice/todo-app/todo-app:13a0ac10
          name: todo-app
          resources: {}
      imagePullSecrets:
        - name: gitlab-regcred
status: {}
